### ISSUE TITLE
deasync@0.1.12 install: 'node ./build.js'

### ISSUE THREAD

**Issue by bilalkhan870** [CloudDesignBox/MSGraphSPFxWebPartExample#1]
1572 verbose cwd C:\SPFx\MSGraphSPFxWebPartExample-master
1573 verbose Windows_NT 10.0.17134
1574 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xyz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "deasync"
1575 verbose node v10.16.0
1576 verbose npm  v6.10.0
1577 error code ELIFECYCLE
1578 error errno 1
1579 error deasync@0.1.12 install: `node ./build.js`
1579 error Exit status 1
1580 error Failed at the deasync@0.1.12 install script.
1580 error This is probably not a problem with npm. There is likely additional logging output above.
1581 verbose exit [ 1, true ]

can you pls me on this regards 

Thanks in advance 

@CloudDesignBox

**Comment by CloudDesignBox** [comment]
Hi @bilalkhan870 ,

It looks like a problem in the build process, which version of npm do you have installed?

**Comment by bilalkhan870** [comment]
![image](https://user-images.githubusercontent.com/39082648/61587931-55900980-aba4-11e9-86a9-e9b56277cfe2.png)

Can you pls upload SPPKG file ?
Thanks in advance

@CloudDesignBox

**Comment by CloudDesignBox** [comment]
Hi @bilalkhan870 

That looks like the right version. This tutorial was made using the preview version of Graph support. This should still compile and i would probably recommend clearing your NPM cache and reinstalling nodeJs if you still get the issue (with a machine restart in between).

When you finally get the project to build, you may find that the web part doesn't work anymore as it was based on the preview release of Graph in SPFx. You may want to follow the instructions below on how you can do this in the full release of the SPFx Graph support. You can find instructions here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial

**Comment by bilalkhan870** [comment]
Hi @CloudDesignBox 

FYI 

![image](https://user-images.githubusercontent.com/39082648/61851325-ab77f080-aec7-11e9-9cdb-e813f72c5632.png)


thanks

**Comment by CloudDesignBox** [comment]
Hi @bilalkhan870 

Yes this is the problem described in my last post. You are using the preview version of graph. You should be able to build a brand new project following the steps here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial. You should then be able to copy in lines 27 to 39 to get it to work using the latest version.

Thanks,
Tony

**Comment by bilalkhan870** [comment]
Thank you so much @CloudDesignBox
